version: "3"
services:

  incident-application-form:
    build: ./incident-application-form
    image: fsa/incident-application-form
    restart: always
    environment:
      - LOOKUP_API_BASE_URL=http://localhost:3000
      - SESSION_KEY=03978Xjb19nh6mR9kQ6B
    ports:
      - "3000:3000"
    command: npm start

  test-hooks:
    build: ./test-hooks
    image: fsa/test-hooks
    restart: always
    ports:
      - "3069:3069"
    command: npm start
