version: "3"
services:

  incident-application-form:
    build: ./incident-application-form
    image: fsa/incident-application-form
    restart: always
    environment:
      - LOOKUP_API_BASE_URL=http://localhost:3000
    ports:
      - "3000:3000"
    command: npm start
